group_prop_dict = {'Dark Purple': ('Mediterranean Avenue',
                                   'Baltic Avenue'),
                   'Light Blue': ('Oriental Avenue',
                                  'Vermont Avenue',
                                  'Connecticut Avenue'),
                   'Pink': ('St. Charles Place',
                            'States Avenue',
                            'Virginia Avenue'),
                   'Orange': ('St. James Place',
                              'Tennessee Avenue',
                              'New York Avenue'),
                   'Red': ('Kentucky Avenue',
                           'Indiana Avenue',
                           'Illinois Avenue'),
                   'Yellow': ('Atlantic Avenue',
                              'Ventnor Avenue',
                              'Marvin Gardens'),
                   'Green': ('Pacific Avenue',
                             'North Carolina Avenue',
                             'Pennsylvania Avenue'),
                   'Dark Blue': ('Park Place',
                                 'Boardwalk'),
                   'Stations': ('Reading Railroad',
                                'Pennsylvania Railroad',
                                'B. & O. Railroad',
                                'Short Line'),
                   'Utilities': ('Electric Company',
                                 'Water Works')}
